server:
  port: 8087

spring:
  datasource:
    username: root
    password: 2337759353Jian!
    url: jdbc:mysql://114.55.137.125:3306/pesys?useUnicode=true&characterEncoding=utf8&useSSL=false&useSeverPreStmts=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.example.mingguang.pojo
  mapper-locations: classpath:/mapper/*.xml